server:
  port: ${SERVER_PORT:9090}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/personal_development}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update